{
 "title": "Fastly real-time Copy",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "regions", "query": { "query": "label_values(reg) " } },
   {
    "name": "pops",
    "query": {
     "query": "label_values(requests{reg=~\".*($regions).*\"} ,pop) "
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "transfered bytes per $interval - WW and regions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(body_size[$interval]))",
     "legendFormat": "WW"
    },
    {
     "expr": "sum(increase(body_size{reg=~\".*($regions).*\"}[$interval])) by (reg)",
     "legendFormat": "{{reg}}"
    }
   ]
  },
  {
   "title": "transfered rate per $interval - WW and regions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(body_size[$interval]))",
     "legendFormat": "WW"
    },
    {
     "expr": "sum(rate(body_size{reg=~\".*($regions).*\"}[$interval])) by (reg)",
     "legendFormat": "{{reg}}"
    }
   ]
  },
  {
   "title": "transfered bytes per $interval - PoPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(body_size{pop=~\".*($pops).*\",reg=~\".*($regions).*\"}[$interval])) by (pop,reg)",
     "legendFormat": "{{reg}} - {{pop}}"
    }
   ]
  },
  {
   "title": "transfered rate per $interval - PoPs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(body_size{pop=~\".*($pops).*\",reg=~\".*($regions).*\"}[$interval])) by (pop,reg)",
     "legendFormat": "{{reg}} - {{pop}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio - WW ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum( increase(edge_hit_requests[$interval]))/( sum(increase(edge_hit_requests[$interval])) + sum(increase(edge_miss_requests[$interval])) + sum(increase(pass[$interval])))",
     "legendFormat": "WW"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio per Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Ratio - regions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (sum(increase(edge_hit_requests{reg=~\".*($regions).*\"}[$interval])) by (reg)) /( (sum(increase(edge_hit_requests{reg=~\".*($regions).*\"}[$interval])) by (reg)) + (sum(increase(edge_miss_requests{reg=~\".*($regions).*\"}[$interval])) by (reg)) + (sum(increase(pass{reg=~\".*($regions).*\"}[$interval])) by (reg)) )",
       "legendFormat": "{{reg}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Ratio per PoP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Ratio - PoPs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (sum(increase(edge_hit_requests{pop=~\".*($pops).*\",reg=~\".*($regions).*\"}[$interval])) by (reg,pop)) /( (sum(increase(edge_hit_requests{pop=~\".*($pops).*\",reg=~\".*($regions).*\"}[$interval])) by (reg,pop)) + (sum(increase(edge_miss_requests{pop=~\".*($pops).*\",reg=~\".*($regions).*\"}[$interval])) by (reg,pop)) + (sum(increase(pass{pop=~\".*($pops).*\",reg=~\".*($regions).*\"}[$interval])) by (reg,pop)) )",
       "legendFormat": "{{reg}} - {{pop}}"
      }
     ]
    }
   ]
  },
  { "title": "Miss latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "miss latency - 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (reg,le) (rate(miss_histogram_bucket[$interval])))",
     "legendFormat": "{{reg}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(miss_histogram_bucket[$interval])))",
     "legendFormat": "WW"
    }
   ]
  },
  {
   "title": "miss latency - 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (pop, reg,le) (rate(miss_histogram_bucket[$interval])))",
     "legendFormat": "{{reg}} - {{pop}}"
    }
   ]
  }
 ]
}